### ISSUE TITLE
Last Step error

### ISSUE THREAD

**Issue by punithan328** [rishabh-s-t/Vastra-Final#1]
@rishabh-s-t 
Constructing DeepLabv3+ model...
Number of classes: 20
Output stride: 16
Number of Input Channels: 3
Traceback (most recent call last):
  File "/Graphonomy-master/exp/inference/inference.py", line 191, in <module>
    x = torch.load(opts.loadmodel)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './inference.pth'
[ WARN:0@41.735] global loadsave.cpp:248 findDecoder imread_('./resized_segmentation_img.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "//main.py", line 44, in <module>
    mask_img=cv2.resize(mask_img,(768,1024))
cv2.error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

What to do Help !

**Comment by punithan328** [comment]
@rishabh-s-t  HELP PLEASE !

**Comment by ahm3d-khanzada12** [comment]
python3: can't open file '/Vastra-Final/detectron2/projects/DensePose/apply_net.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Vastra-Final/get_densepose.py", line 27, in <module>
    with open('./data.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data.json'


I have almost resolved all the issues, but I am stuck on this part. Please connect with me as soon as possible; I have some questions.

**Comment by Omkar-Terdal** [comment]
HI for me dense pose is not generating correctly and remaining all taks are working 
![image](https://github.com/user-attachments/assets/08a783d2-4cb3-47ad-b1dc-fd22fbb8716e)

**Comment by Omkar-Terdal** [comment]
please contact me as soon as possible

**Comment by ankan8145** [comment]
> python3: can't open file '/Vastra-Final/detectron2/projects/DensePose/apply_net.py': [Errno 2] No such file or directory Traceback (most recent call last): File "/Vastra-Final/get_densepose.py", line 27, in with open('./data.json', 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: './data.json'
> 
> I have almost resolved all the issues, but I am stuck on this part. Please connect with me as soon as possible; I have some questions.

I tried but can't find this data.json file, it could be generated by some other script, which is not provided.

**Comment by Omkar-Terdal** [comment]
you are saying data.json file automatically generates from given file then
why its giving error can you ask to you teammates

Omkar terdal

**Comment by rohini-raghu** [comment]
@Omkar-Terdal @ankan8145  can you share data.json file I am getting same error as @ankan8145 
or can you refer to different working project for tryon? That will be a great help
